# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c8b024c12e406a341ce42bfacadb7ea3f689ae17edc2b945838c36d8633240ebf358886e75b9fdce92b067b08f528e77747f8c85cf74cd32e2fd68a47cf7dca

test:
  secret_key_base: 1a657ea217ee893eb1717bcbc86acfcbe3396c7e0a532fd55886fbb08cf3e8a7e8d790db1c7c5a4aaa2e0de725d3d1653a4d91222686321d5c3b7be5783f2799

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
